# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/simulator/request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/simulator/request.proto',
  package='roadwork.simulator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n services/simulator/request.proto\x12\x12roadwork.simulator\"A\n\x0bStepRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\x12\x0e\n\x06render\x18\x03 \x01(\x08\"\"\n\x0cResetRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\"1\n\rRenderRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\"\"\n\x0c\x43loseRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\"\x1e\n\rCreateRequest\x12\r\n\x05\x65nvId\x18\x01 \x01(\t\".\n\x18\x41\x63tionSpaceSampleRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\",\n\x16\x41\x63tionSpaceInfoRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\"1\n\x1bObservationSpaceInfoRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\tb\x06proto3')
)




_STEPREQUEST = _descriptor.Descriptor(
  name='StepRequest',
  full_name='roadwork.simulator.StepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.StepRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='roadwork.simulator.StepRequest.action', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='render', full_name='roadwork.simulator.StepRequest.render', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=121,
)


_RESETREQUEST = _descriptor.Descriptor(
  name='ResetRequest',
  full_name='roadwork.simulator.ResetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.ResetRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=157,
)


_RENDERREQUEST = _descriptor.Descriptor(
  name='RenderRequest',
  full_name='roadwork.simulator.RenderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.RenderRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='roadwork.simulator.RenderRequest.mode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=208,
)


_CLOSEREQUEST = _descriptor.Descriptor(
  name='CloseRequest',
  full_name='roadwork.simulator.CloseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.CloseRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=244,
)


_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='roadwork.simulator.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='envId', full_name='roadwork.simulator.CreateRequest.envId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=276,
)


_ACTIONSPACESAMPLEREQUEST = _descriptor.Descriptor(
  name='ActionSpaceSampleRequest',
  full_name='roadwork.simulator.ActionSpaceSampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.ActionSpaceSampleRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=324,
)


_ACTIONSPACEINFOREQUEST = _descriptor.Descriptor(
  name='ActionSpaceInfoRequest',
  full_name='roadwork.simulator.ActionSpaceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.ActionSpaceInfoRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=370,
)


_OBSERVATIONSPACEINFOREQUEST = _descriptor.Descriptor(
  name='ObservationSpaceInfoRequest',
  full_name='roadwork.simulator.ObservationSpaceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.ObservationSpaceInfoRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=421,
)

DESCRIPTOR.message_types_by_name['StepRequest'] = _STEPREQUEST
DESCRIPTOR.message_types_by_name['ResetRequest'] = _RESETREQUEST
DESCRIPTOR.message_types_by_name['RenderRequest'] = _RENDERREQUEST
DESCRIPTOR.message_types_by_name['CloseRequest'] = _CLOSEREQUEST
DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['ActionSpaceSampleRequest'] = _ACTIONSPACESAMPLEREQUEST
DESCRIPTOR.message_types_by_name['ActionSpaceInfoRequest'] = _ACTIONSPACEINFOREQUEST
DESCRIPTOR.message_types_by_name['ObservationSpaceInfoRequest'] = _OBSERVATIONSPACEINFOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StepRequest = _reflection.GeneratedProtocolMessageType('StepRequest', (_message.Message,), {
  'DESCRIPTOR' : _STEPREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.StepRequest)
  })
_sym_db.RegisterMessage(StepRequest)

ResetRequest = _reflection.GeneratedProtocolMessageType('ResetRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ResetRequest)
  })
_sym_db.RegisterMessage(ResetRequest)

RenderRequest = _reflection.GeneratedProtocolMessageType('RenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.RenderRequest)
  })
_sym_db.RegisterMessage(RenderRequest)

CloseRequest = _reflection.GeneratedProtocolMessageType('CloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.CloseRequest)
  })
_sym_db.RegisterMessage(CloseRequest)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

ActionSpaceSampleRequest = _reflection.GeneratedProtocolMessageType('ActionSpaceSampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSPACESAMPLEREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ActionSpaceSampleRequest)
  })
_sym_db.RegisterMessage(ActionSpaceSampleRequest)

ActionSpaceInfoRequest = _reflection.GeneratedProtocolMessageType('ActionSpaceInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSPACEINFOREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ActionSpaceInfoRequest)
  })
_sym_db.RegisterMessage(ActionSpaceInfoRequest)

ObservationSpaceInfoRequest = _reflection.GeneratedProtocolMessageType('ObservationSpaceInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONSPACEINFOREQUEST,
  '__module__' : 'services.simulator.request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ObservationSpaceInfoRequest)
  })
_sym_db.RegisterMessage(ObservationSpaceInfoRequest)


# @@protoc_insertion_point(module_scope)
