# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/simulator/response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from system import space_pb2 as system_dot_space__pb2
from system import space_meta_pb2 as system_dot_space__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/simulator/response.proto',
  package='roadwork.simulator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!services/simulator/response.proto\x12\x12roadwork.simulator\x1a\x12system/space.proto\x1a\x17system/space_meta.proto\"\xc9\x01\n\x0cStepResponse\x12\x0e\n\x06reward\x18\x01 \x01(\x02\x12\x0e\n\x06isDone\x18\x02 \x01(\x08\x12\x38\n\x04info\x18\x03 \x03(\x0b\x32*.roadwork.simulator.StepResponse.InfoEntry\x12\x32\n\x0bobservation\x18\x04 \x01(\x0b\x32\x1d.roadwork.system.SpaceWrapper\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"$\n\rResetResponse\x12\x13\n\x0bobservation\x18\x01 \x03(\x01\"\x10\n\x0eRenderResponse\"\x0f\n\rCloseResponse\"$\n\x0e\x43reateResponse\x12\x12\n\ninstanceId\x18\x01 \x01(\t\"+\n\x19\x41\x63tionSpaceSampleResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\"L\n\x17\x41\x63tionSpaceInfoResponse\x12\x31\n\x06result\x18\x01 \x01(\x0b\x32!.roadwork.system.MetaSpaceWrapper\"Q\n\x1cObservationSpaceInfoResponse\x12\x31\n\x06result\x18\x01 \x01(\x0b\x32!.roadwork.system.MetaSpaceWrapperb\x06proto3')
  ,
  dependencies=[system_dot_space__pb2.DESCRIPTOR,system_dot_space__meta__pb2.DESCRIPTOR,])




_STEPRESPONSE_INFOENTRY = _descriptor.Descriptor(
  name='InfoEntry',
  full_name='roadwork.simulator.StepResponse.InfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='roadwork.simulator.StepResponse.InfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='roadwork.simulator.StepResponse.InfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=304,
)

_STEPRESPONSE = _descriptor.Descriptor(
  name='StepResponse',
  full_name='roadwork.simulator.StepResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='roadwork.simulator.StepResponse.reward', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDone', full_name='roadwork.simulator.StepResponse.isDone', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='roadwork.simulator.StepResponse.info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation', full_name='roadwork.simulator.StepResponse.observation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STEPRESPONSE_INFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=304,
)


_RESETRESPONSE = _descriptor.Descriptor(
  name='ResetResponse',
  full_name='roadwork.simulator.ResetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='roadwork.simulator.ResetResponse.observation', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=342,
)


_RENDERRESPONSE = _descriptor.Descriptor(
  name='RenderResponse',
  full_name='roadwork.simulator.RenderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=360,
)


_CLOSERESPONSE = _descriptor.Descriptor(
  name='CloseResponse',
  full_name='roadwork.simulator.CloseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=377,
)


_CREATERESPONSE = _descriptor.Descriptor(
  name='CreateResponse',
  full_name='roadwork.simulator.CreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.simulator.CreateResponse.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=415,
)


_ACTIONSPACESAMPLERESPONSE = _descriptor.Descriptor(
  name='ActionSpaceSampleResponse',
  full_name='roadwork.simulator.ActionSpaceSampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='roadwork.simulator.ActionSpaceSampleResponse.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=460,
)


_ACTIONSPACEINFORESPONSE = _descriptor.Descriptor(
  name='ActionSpaceInfoResponse',
  full_name='roadwork.simulator.ActionSpaceInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='roadwork.simulator.ActionSpaceInfoResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=538,
)


_OBSERVATIONSPACEINFORESPONSE = _descriptor.Descriptor(
  name='ObservationSpaceInfoResponse',
  full_name='roadwork.simulator.ObservationSpaceInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='roadwork.simulator.ObservationSpaceInfoResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=621,
)

_STEPRESPONSE_INFOENTRY.containing_type = _STEPRESPONSE
_STEPRESPONSE.fields_by_name['info'].message_type = _STEPRESPONSE_INFOENTRY
_STEPRESPONSE.fields_by_name['observation'].message_type = system_dot_space__pb2._SPACEWRAPPER
_ACTIONSPACEINFORESPONSE.fields_by_name['result'].message_type = system_dot_space__meta__pb2._METASPACEWRAPPER
_OBSERVATIONSPACEINFORESPONSE.fields_by_name['result'].message_type = system_dot_space__meta__pb2._METASPACEWRAPPER
DESCRIPTOR.message_types_by_name['StepResponse'] = _STEPRESPONSE
DESCRIPTOR.message_types_by_name['ResetResponse'] = _RESETRESPONSE
DESCRIPTOR.message_types_by_name['RenderResponse'] = _RENDERRESPONSE
DESCRIPTOR.message_types_by_name['CloseResponse'] = _CLOSERESPONSE
DESCRIPTOR.message_types_by_name['CreateResponse'] = _CREATERESPONSE
DESCRIPTOR.message_types_by_name['ActionSpaceSampleResponse'] = _ACTIONSPACESAMPLERESPONSE
DESCRIPTOR.message_types_by_name['ActionSpaceInfoResponse'] = _ACTIONSPACEINFORESPONSE
DESCRIPTOR.message_types_by_name['ObservationSpaceInfoResponse'] = _OBSERVATIONSPACEINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StepResponse = _reflection.GeneratedProtocolMessageType('StepResponse', (_message.Message,), {

  'InfoEntry' : _reflection.GeneratedProtocolMessageType('InfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _STEPRESPONSE_INFOENTRY,
    '__module__' : 'services.simulator.response_pb2'
    # @@protoc_insertion_point(class_scope:roadwork.simulator.StepResponse.InfoEntry)
    })
  ,
  'DESCRIPTOR' : _STEPRESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.StepResponse)
  })
_sym_db.RegisterMessage(StepResponse)
_sym_db.RegisterMessage(StepResponse.InfoEntry)

ResetResponse = _reflection.GeneratedProtocolMessageType('ResetResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETRESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ResetResponse)
  })
_sym_db.RegisterMessage(ResetResponse)

RenderResponse = _reflection.GeneratedProtocolMessageType('RenderResponse', (_message.Message,), {
  'DESCRIPTOR' : _RENDERRESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.RenderResponse)
  })
_sym_db.RegisterMessage(RenderResponse)

CloseResponse = _reflection.GeneratedProtocolMessageType('CloseResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOSERESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.CloseResponse)
  })
_sym_db.RegisterMessage(CloseResponse)

CreateResponse = _reflection.GeneratedProtocolMessageType('CreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.CreateResponse)
  })
_sym_db.RegisterMessage(CreateResponse)

ActionSpaceSampleResponse = _reflection.GeneratedProtocolMessageType('ActionSpaceSampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSPACESAMPLERESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ActionSpaceSampleResponse)
  })
_sym_db.RegisterMessage(ActionSpaceSampleResponse)

ActionSpaceInfoResponse = _reflection.GeneratedProtocolMessageType('ActionSpaceInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSPACEINFORESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ActionSpaceInfoResponse)
  })
_sym_db.RegisterMessage(ActionSpaceInfoResponse)

ObservationSpaceInfoResponse = _reflection.GeneratedProtocolMessageType('ObservationSpaceInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONSPACEINFORESPONSE,
  '__module__' : 'services.simulator.response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.simulator.ObservationSpaceInfoResponse)
  })
_sym_db.RegisterMessage(ObservationSpaceInfoResponse)


_STEPRESPONSE_INFOENTRY._options = None
# @@protoc_insertion_point(module_scope)
