# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system/base_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system/base_response.proto',
  package='roadwork.system',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1asystem/base_response.proto\x12\x0froadwork.system\"\x0e\n\x0c\x42\x61seResponseb\x06proto3')
)




_BASERESPONSE = _descriptor.Descriptor(
  name='BaseResponse',
  full_name='roadwork.system.BaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['BaseResponse'] = _BASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'system.base_response_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)


# @@protoc_insertion_point(module_scope)
