# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from services.simulator import request_pb2 as services_dot_simulator_dot_request__pb2
from services.simulator import response_pb2 as services_dot_simulator_dot_response__pb2
from system import base_request_pb2 as system_dot_base__request__pb2
from system import base_response_pb2 as system_dot_base__response__pb2


class SimulatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/roadwork.simulator.Simulator/Create',
        request_serializer=services_dot_simulator_dot_request__pb2.CreateRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.CreateResponse.FromString,
        )
    self.Step = channel.unary_unary(
        '/roadwork.simulator.Simulator/Step',
        request_serializer=services_dot_simulator_dot_request__pb2.StepRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.StepResponse.FromString,
        )
    self.Reset = channel.unary_unary(
        '/roadwork.simulator.Simulator/Reset',
        request_serializer=services_dot_simulator_dot_request__pb2.ResetRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.ResetResponse.FromString,
        )
    self.Render = channel.unary_unary(
        '/roadwork.simulator.Simulator/Render',
        request_serializer=services_dot_simulator_dot_request__pb2.RenderRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.RenderResponse.FromString,
        )
    self.Close = channel.unary_unary(
        '/roadwork.simulator.Simulator/Close',
        request_serializer=services_dot_simulator_dot_request__pb2.CloseRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.CloseResponse.FromString,
        )
    self.ActionSpaceSample = channel.unary_unary(
        '/roadwork.simulator.Simulator/ActionSpaceSample',
        request_serializer=services_dot_simulator_dot_request__pb2.ActionSpaceSampleRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.ActionSpaceSampleResponse.FromString,
        )
    self.ActionSpaceInfo = channel.unary_unary(
        '/roadwork.simulator.Simulator/ActionSpaceInfo',
        request_serializer=services_dot_simulator_dot_request__pb2.ActionSpaceInfoRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.ActionSpaceInfoResponse.FromString,
        )
    self.ObservationSpaceInfo = channel.unary_unary(
        '/roadwork.simulator.Simulator/ObservationSpaceInfo',
        request_serializer=services_dot_simulator_dot_request__pb2.ObservationSpaceInfoRequest.SerializeToString,
        response_deserializer=services_dot_simulator_dot_response__pb2.ObservationSpaceInfoResponse.FromString,
        )
    self.MonitorStart = channel.unary_unary(
        '/roadwork.simulator.Simulator/MonitorStart',
        request_serializer=system_dot_base__request__pb2.BaseRequest.SerializeToString,
        response_deserializer=system_dot_base__response__pb2.BaseResponse.FromString,
        )
    self.MonitorStop = channel.unary_unary(
        '/roadwork.simulator.Simulator/MonitorStop',
        request_serializer=system_dot_base__request__pb2.BaseRequest.SerializeToString,
        response_deserializer=system_dot_base__response__pb2.BaseResponse.FromString,
        )


class SimulatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Step(self, request, context):
    """Run one timestep of the environment's dynamics. When end of
    episode is reached, you are responsible for calling `reset()`
    to reset this environment's state.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    """Resets the state of the environment and returns an initial observation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Render(self, request, context):
    """Renders the environment.
    The set of supported modes varies per environment. (And some
    environments do not support rendering at all.) By convention,
    if mode is:
    - human: render to the current display or terminal and
    return nothing. Usually for human consumption.
    - rgb_array: Return an numpy.ndarray with shape (x, y, 3),
    representing RGB values for an x-by-y pixel image, suitable
    for turning into a video.
    - ansi: Return a string (str) or StringIO.StringIO containing a
    terminal-style text representation. The text can include newlines
    and ANSI escape sequences (e.g. for colors).
    Note:
    Make sure that your class's metadata 'render.modes' key includes
    the list of supported modes. It's recommended to call super()
    in implementations to use the functionality of this method.
    Args:
    mode (str): the mode to render with
    Example:
    class MyEnv(Env):
    metadata = {'render.modes': ['human', 'rgb_array']}
    def render(self, mode='human'):
    if mode == 'rgb_array':
    return np.array(...) # return RGB frame suitable for video
    elif mode == 'human':
    ... # pop up a window and render
    else:
    super(MyEnv, self).render(mode=mode) # just raise an exception
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Close(self, request, context):
    """Override close in your subclass to perform any necessary cleanup.
    Environments will automatically close() themselves when
    garbage collected or when the program exits.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ActionSpaceSample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ActionSpaceInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ObservationSpaceInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MonitorStart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MonitorStop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=services_dot_simulator_dot_request__pb2.CreateRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.CreateResponse.SerializeToString,
      ),
      'Step': grpc.unary_unary_rpc_method_handler(
          servicer.Step,
          request_deserializer=services_dot_simulator_dot_request__pb2.StepRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.StepResponse.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=services_dot_simulator_dot_request__pb2.ResetRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.ResetResponse.SerializeToString,
      ),
      'Render': grpc.unary_unary_rpc_method_handler(
          servicer.Render,
          request_deserializer=services_dot_simulator_dot_request__pb2.RenderRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.RenderResponse.SerializeToString,
      ),
      'Close': grpc.unary_unary_rpc_method_handler(
          servicer.Close,
          request_deserializer=services_dot_simulator_dot_request__pb2.CloseRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.CloseResponse.SerializeToString,
      ),
      'ActionSpaceSample': grpc.unary_unary_rpc_method_handler(
          servicer.ActionSpaceSample,
          request_deserializer=services_dot_simulator_dot_request__pb2.ActionSpaceSampleRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.ActionSpaceSampleResponse.SerializeToString,
      ),
      'ActionSpaceInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ActionSpaceInfo,
          request_deserializer=services_dot_simulator_dot_request__pb2.ActionSpaceInfoRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.ActionSpaceInfoResponse.SerializeToString,
      ),
      'ObservationSpaceInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ObservationSpaceInfo,
          request_deserializer=services_dot_simulator_dot_request__pb2.ObservationSpaceInfoRequest.FromString,
          response_serializer=services_dot_simulator_dot_response__pb2.ObservationSpaceInfoResponse.SerializeToString,
      ),
      'MonitorStart': grpc.unary_unary_rpc_method_handler(
          servicer.MonitorStart,
          request_deserializer=system_dot_base__request__pb2.BaseRequest.FromString,
          response_serializer=system_dot_base__response__pb2.BaseResponse.SerializeToString,
      ),
      'MonitorStop': grpc.unary_unary_rpc_method_handler(
          servicer.MonitorStop,
          request_deserializer=system_dot_base__request__pb2.BaseRequest.FromString,
          response_serializer=system_dot_base__response__pb2.BaseResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'roadwork.simulator.Simulator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
