# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/simulator/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from system import base_response_pb2 as system_dot_base__response__pb2
from system import base_request_pb2 as system_dot_base__request__pb2
from services.simulator import request_pb2 as services_dot_simulator_dot_request__pb2
from services.simulator import response_pb2 as services_dot_simulator_dot_response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/simulator/service.proto',
  package='roadwork.simulator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n services/simulator/service.proto\x12\x12roadwork.simulator\x1a\x1asystem/base_response.proto\x1a\x19system/base_request.proto\x1a services/simulator/request.proto\x1a!services/simulator/response.proto2\x9a\x07\n\tSimulator\x12Q\n\x06\x43reate\x12!.roadwork.simulator.CreateRequest\x1a\".roadwork.simulator.CreateResponse\"\x00\x12K\n\x04Step\x12\x1f.roadwork.simulator.StepRequest\x1a .roadwork.simulator.StepResponse\"\x00\x12N\n\x05Reset\x12 .roadwork.simulator.ResetRequest\x1a!.roadwork.simulator.ResetResponse\"\x00\x12Q\n\x06Render\x12!.roadwork.simulator.RenderRequest\x1a\".roadwork.simulator.RenderResponse\"\x00\x12N\n\x05\x43lose\x12 .roadwork.simulator.CloseRequest\x1a!.roadwork.simulator.CloseResponse\"\x00\x12r\n\x11\x41\x63tionSpaceSample\x12,.roadwork.simulator.ActionSpaceSampleRequest\x1a-.roadwork.simulator.ActionSpaceSampleResponse\"\x00\x12l\n\x0f\x41\x63tionSpaceInfo\x12*.roadwork.simulator.ActionSpaceInfoRequest\x1a+.roadwork.simulator.ActionSpaceInfoResponse\"\x00\x12{\n\x14ObservationSpaceInfo\x12/.roadwork.simulator.ObservationSpaceInfoRequest\x1a\x30.roadwork.simulator.ObservationSpaceInfoResponse\"\x00\x12M\n\x0cMonitorStart\x12\x1c.roadwork.system.BaseRequest\x1a\x1d.roadwork.system.BaseResponse\"\x00\x12L\n\x0bMonitorStop\x12\x1c.roadwork.system.BaseRequest\x1a\x1d.roadwork.system.BaseResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[system_dot_base__response__pb2.DESCRIPTOR,system_dot_base__request__pb2.DESCRIPTOR,services_dot_simulator_dot_request__pb2.DESCRIPTOR,services_dot_simulator_dot_response__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SIMULATOR = _descriptor.ServiceDescriptor(
  name='Simulator',
  full_name='roadwork.simulator.Simulator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=181,
  serialized_end=1103,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='roadwork.simulator.Simulator.Create',
    index=0,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._CREATEREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._CREATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Step',
    full_name='roadwork.simulator.Simulator.Step',
    index=1,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._STEPREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._STEPRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Reset',
    full_name='roadwork.simulator.Simulator.Reset',
    index=2,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._RESETREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._RESETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Render',
    full_name='roadwork.simulator.Simulator.Render',
    index=3,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._RENDERREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._RENDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='roadwork.simulator.Simulator.Close',
    index=4,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._CLOSEREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._CLOSERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ActionSpaceSample',
    full_name='roadwork.simulator.Simulator.ActionSpaceSample',
    index=5,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._ACTIONSPACESAMPLEREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._ACTIONSPACESAMPLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ActionSpaceInfo',
    full_name='roadwork.simulator.Simulator.ActionSpaceInfo',
    index=6,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._ACTIONSPACEINFOREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._ACTIONSPACEINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ObservationSpaceInfo',
    full_name='roadwork.simulator.Simulator.ObservationSpaceInfo',
    index=7,
    containing_service=None,
    input_type=services_dot_simulator_dot_request__pb2._OBSERVATIONSPACEINFOREQUEST,
    output_type=services_dot_simulator_dot_response__pb2._OBSERVATIONSPACEINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MonitorStart',
    full_name='roadwork.simulator.Simulator.MonitorStart',
    index=8,
    containing_service=None,
    input_type=system_dot_base__request__pb2._BASEREQUEST,
    output_type=system_dot_base__response__pb2._BASERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MonitorStop',
    full_name='roadwork.simulator.Simulator.MonitorStop',
    index=9,
    containing_service=None,
    input_type=system_dot_base__request__pb2._BASEREQUEST,
    output_type=system_dot_base__response__pb2._BASERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATOR)

DESCRIPTOR.services_by_name['Simulator'] = _SIMULATOR

# @@protoc_insertion_point(module_scope)
