# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system/base_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system/base_request.proto',
  package='roadwork.system',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19system/base_request.proto\x12\x0froadwork.system\"!\n\x0b\x42\x61seRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\tb\x06proto3')
)




_BASEREQUEST = _descriptor.Descriptor(
  name='BaseRequest',
  full_name='roadwork.system.BaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='roadwork.system.BaseRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['BaseRequest'] = _BASEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseRequest = _reflection.GeneratedProtocolMessageType('BaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEREQUEST,
  '__module__' : 'system.base_request_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.BaseRequest)
  })
_sym_db.RegisterMessage(BaseRequest)


# @@protoc_insertion_point(module_scope)
