# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system/space.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system/space.proto',
  package='roadwork.system',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12system/space.proto\x12\x0froadwork.system\"\xa2\x01\n\x0cSpaceWrapper\x12(\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x19.roadwork.system.SpaceBoxH\x00\x12\x32\n\x08\x64iscrete\x18\x02 \x01(\x0b\x32\x1e.roadwork.system.SpaceDiscreteH\x00\x12,\n\x05tuple\x18\x03 \x01(\x0b\x32\x1b.roadwork.system.SpaceTupleH\x00\x42\x06\n\x04type\"$\n\rSpaceDiscrete\x12\x13\n\x0bobservation\x18\x01 \x01(\x05\"\x1f\n\x08SpaceBox\x12\x13\n\x0bobservation\x18\x01 \x03(\x01\";\n\nSpaceTuple\x12-\n\x06tuples\x18\x01 \x03(\x0b\x32\x1d.roadwork.system.SpaceWrapperb\x06proto3')
)




_SPACEWRAPPER = _descriptor.Descriptor(
  name='SpaceWrapper',
  full_name='roadwork.system.SpaceWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='roadwork.system.SpaceWrapper.box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discrete', full_name='roadwork.system.SpaceWrapper.discrete', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tuple', full_name='roadwork.system.SpaceWrapper.tuple', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='roadwork.system.SpaceWrapper.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=40,
  serialized_end=202,
)


_SPACEDISCRETE = _descriptor.Descriptor(
  name='SpaceDiscrete',
  full_name='roadwork.system.SpaceDiscrete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='roadwork.system.SpaceDiscrete.observation', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=240,
)


_SPACEBOX = _descriptor.Descriptor(
  name='SpaceBox',
  full_name='roadwork.system.SpaceBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='roadwork.system.SpaceBox.observation', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=273,
)


_SPACETUPLE = _descriptor.Descriptor(
  name='SpaceTuple',
  full_name='roadwork.system.SpaceTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tuples', full_name='roadwork.system.SpaceTuple.tuples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=334,
)

_SPACEWRAPPER.fields_by_name['box'].message_type = _SPACEBOX
_SPACEWRAPPER.fields_by_name['discrete'].message_type = _SPACEDISCRETE
_SPACEWRAPPER.fields_by_name['tuple'].message_type = _SPACETUPLE
_SPACEWRAPPER.oneofs_by_name['type'].fields.append(
  _SPACEWRAPPER.fields_by_name['box'])
_SPACEWRAPPER.fields_by_name['box'].containing_oneof = _SPACEWRAPPER.oneofs_by_name['type']
_SPACEWRAPPER.oneofs_by_name['type'].fields.append(
  _SPACEWRAPPER.fields_by_name['discrete'])
_SPACEWRAPPER.fields_by_name['discrete'].containing_oneof = _SPACEWRAPPER.oneofs_by_name['type']
_SPACEWRAPPER.oneofs_by_name['type'].fields.append(
  _SPACEWRAPPER.fields_by_name['tuple'])
_SPACEWRAPPER.fields_by_name['tuple'].containing_oneof = _SPACEWRAPPER.oneofs_by_name['type']
_SPACETUPLE.fields_by_name['tuples'].message_type = _SPACEWRAPPER
DESCRIPTOR.message_types_by_name['SpaceWrapper'] = _SPACEWRAPPER
DESCRIPTOR.message_types_by_name['SpaceDiscrete'] = _SPACEDISCRETE
DESCRIPTOR.message_types_by_name['SpaceBox'] = _SPACEBOX
DESCRIPTOR.message_types_by_name['SpaceTuple'] = _SPACETUPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpaceWrapper = _reflection.GeneratedProtocolMessageType('SpaceWrapper', (_message.Message,), {
  'DESCRIPTOR' : _SPACEWRAPPER,
  '__module__' : 'system.space_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.SpaceWrapper)
  })
_sym_db.RegisterMessage(SpaceWrapper)

SpaceDiscrete = _reflection.GeneratedProtocolMessageType('SpaceDiscrete', (_message.Message,), {
  'DESCRIPTOR' : _SPACEDISCRETE,
  '__module__' : 'system.space_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.SpaceDiscrete)
  })
_sym_db.RegisterMessage(SpaceDiscrete)

SpaceBox = _reflection.GeneratedProtocolMessageType('SpaceBox', (_message.Message,), {
  'DESCRIPTOR' : _SPACEBOX,
  '__module__' : 'system.space_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.SpaceBox)
  })
_sym_db.RegisterMessage(SpaceBox)

SpaceTuple = _reflection.GeneratedProtocolMessageType('SpaceTuple', (_message.Message,), {
  'DESCRIPTOR' : _SPACETUPLE,
  '__module__' : 'system.space_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.SpaceTuple)
  })
_sym_db.RegisterMessage(SpaceTuple)


# @@protoc_insertion_point(module_scope)
