# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system/space_meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system/space_meta.proto',
  package='roadwork.system',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17system/space_meta.proto\x12\x0froadwork.system\"x\n\x0cMetaSpaceBox\x12\x12\n\ndimensions\x18\x01 \x03(\r\x12G\n\x0f\x64imensionDouble\x18\x02 \x01(\x0b\x32,.roadwork.system.MetaSpaceBoxDimensionDoubleH\x00\x42\x0b\n\tdimension\"M\n\x1bMetaSpaceBoxDimensionDouble\x12\x0b\n\x03low\x18\x01 \x03(\x01\x12\x0c\n\x04high\x18\x02 \x03(\x01\x12\x13\n\x0bobservation\x18\x03 \x03(\x01\"\x1e\n\x11MetaSpaceDiscrete\x12\t\n\x01n\x18\x01 \x01(\r\"C\n\x0eMetaSpaceTuple\x12\x31\n\x06spaces\x18\x01 \x03(\x0b\x32!.roadwork.system.MetaSpaceWrapper\"\xb2\x01\n\x10MetaSpaceWrapper\x12,\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x1d.roadwork.system.MetaSpaceBoxH\x00\x12\x36\n\x08\x64iscrete\x18\x02 \x01(\x0b\x32\".roadwork.system.MetaSpaceDiscreteH\x00\x12\x30\n\x05tuple\x18\x03 \x01(\x0b\x32\x1f.roadwork.system.MetaSpaceTupleH\x00\x42\x06\n\x04typeb\x06proto3')
)




_METASPACEBOX = _descriptor.Descriptor(
  name='MetaSpaceBox',
  full_name='roadwork.system.MetaSpaceBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='roadwork.system.MetaSpaceBox.dimensions', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimensionDouble', full_name='roadwork.system.MetaSpaceBox.dimensionDouble', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='dimension', full_name='roadwork.system.MetaSpaceBox.dimension',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=44,
  serialized_end=164,
)


_METASPACEBOXDIMENSIONDOUBLE = _descriptor.Descriptor(
  name='MetaSpaceBoxDimensionDouble',
  full_name='roadwork.system.MetaSpaceBoxDimensionDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='low', full_name='roadwork.system.MetaSpaceBoxDimensionDouble.low', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='roadwork.system.MetaSpaceBoxDimensionDouble.high', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation', full_name='roadwork.system.MetaSpaceBoxDimensionDouble.observation', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=243,
)


_METASPACEDISCRETE = _descriptor.Descriptor(
  name='MetaSpaceDiscrete',
  full_name='roadwork.system.MetaSpaceDiscrete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='roadwork.system.MetaSpaceDiscrete.n', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=275,
)


_METASPACETUPLE = _descriptor.Descriptor(
  name='MetaSpaceTuple',
  full_name='roadwork.system.MetaSpaceTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spaces', full_name='roadwork.system.MetaSpaceTuple.spaces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=344,
)


_METASPACEWRAPPER = _descriptor.Descriptor(
  name='MetaSpaceWrapper',
  full_name='roadwork.system.MetaSpaceWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='roadwork.system.MetaSpaceWrapper.box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discrete', full_name='roadwork.system.MetaSpaceWrapper.discrete', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tuple', full_name='roadwork.system.MetaSpaceWrapper.tuple', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='roadwork.system.MetaSpaceWrapper.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=347,
  serialized_end=525,
)

_METASPACEBOX.fields_by_name['dimensionDouble'].message_type = _METASPACEBOXDIMENSIONDOUBLE
_METASPACEBOX.oneofs_by_name['dimension'].fields.append(
  _METASPACEBOX.fields_by_name['dimensionDouble'])
_METASPACEBOX.fields_by_name['dimensionDouble'].containing_oneof = _METASPACEBOX.oneofs_by_name['dimension']
_METASPACETUPLE.fields_by_name['spaces'].message_type = _METASPACEWRAPPER
_METASPACEWRAPPER.fields_by_name['box'].message_type = _METASPACEBOX
_METASPACEWRAPPER.fields_by_name['discrete'].message_type = _METASPACEDISCRETE
_METASPACEWRAPPER.fields_by_name['tuple'].message_type = _METASPACETUPLE
_METASPACEWRAPPER.oneofs_by_name['type'].fields.append(
  _METASPACEWRAPPER.fields_by_name['box'])
_METASPACEWRAPPER.fields_by_name['box'].containing_oneof = _METASPACEWRAPPER.oneofs_by_name['type']
_METASPACEWRAPPER.oneofs_by_name['type'].fields.append(
  _METASPACEWRAPPER.fields_by_name['discrete'])
_METASPACEWRAPPER.fields_by_name['discrete'].containing_oneof = _METASPACEWRAPPER.oneofs_by_name['type']
_METASPACEWRAPPER.oneofs_by_name['type'].fields.append(
  _METASPACEWRAPPER.fields_by_name['tuple'])
_METASPACEWRAPPER.fields_by_name['tuple'].containing_oneof = _METASPACEWRAPPER.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['MetaSpaceBox'] = _METASPACEBOX
DESCRIPTOR.message_types_by_name['MetaSpaceBoxDimensionDouble'] = _METASPACEBOXDIMENSIONDOUBLE
DESCRIPTOR.message_types_by_name['MetaSpaceDiscrete'] = _METASPACEDISCRETE
DESCRIPTOR.message_types_by_name['MetaSpaceTuple'] = _METASPACETUPLE
DESCRIPTOR.message_types_by_name['MetaSpaceWrapper'] = _METASPACEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaSpaceBox = _reflection.GeneratedProtocolMessageType('MetaSpaceBox', (_message.Message,), {
  'DESCRIPTOR' : _METASPACEBOX,
  '__module__' : 'system.space_meta_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.MetaSpaceBox)
  })
_sym_db.RegisterMessage(MetaSpaceBox)

MetaSpaceBoxDimensionDouble = _reflection.GeneratedProtocolMessageType('MetaSpaceBoxDimensionDouble', (_message.Message,), {
  'DESCRIPTOR' : _METASPACEBOXDIMENSIONDOUBLE,
  '__module__' : 'system.space_meta_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.MetaSpaceBoxDimensionDouble)
  })
_sym_db.RegisterMessage(MetaSpaceBoxDimensionDouble)

MetaSpaceDiscrete = _reflection.GeneratedProtocolMessageType('MetaSpaceDiscrete', (_message.Message,), {
  'DESCRIPTOR' : _METASPACEDISCRETE,
  '__module__' : 'system.space_meta_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.MetaSpaceDiscrete)
  })
_sym_db.RegisterMessage(MetaSpaceDiscrete)

MetaSpaceTuple = _reflection.GeneratedProtocolMessageType('MetaSpaceTuple', (_message.Message,), {
  'DESCRIPTOR' : _METASPACETUPLE,
  '__module__' : 'system.space_meta_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.MetaSpaceTuple)
  })
_sym_db.RegisterMessage(MetaSpaceTuple)

MetaSpaceWrapper = _reflection.GeneratedProtocolMessageType('MetaSpaceWrapper', (_message.Message,), {
  'DESCRIPTOR' : _METASPACEWRAPPER,
  '__module__' : 'system.space_meta_pb2'
  # @@protoc_insertion_point(class_scope:roadwork.system.MetaSpaceWrapper)
  })
_sym_db.RegisterMessage(MetaSpaceWrapper)


# @@protoc_insertion_point(module_scope)
