apiVersion: v1
kind: Pod
metadata:
  labels: # Labels for the POD
  name: p-rw-client-python-cartpole # pod-roadwork-...
  annotations:
    dapr.io/enabled: "true" # Do we inject a sidecar to this deployment?
    dapr.io/id: "id-rw-client-python-cartpole" # Unique ID or Name for Dapr App (so we can communicate with it)
    dapr.io/protocol: "grpc"
spec:
  containers:
  - name: c-rw-client-python-cartpole # Name of our container, e.g. `kubectl logs -c c-rw-...`
    image: roadwork/rw-client-python-cartpole:latest
    imagePullPolicy: Never # Production: Always or NotIfPresent
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
  restartPolicy: OnFailure # OnFailure since sometimes we fail to identify the GRPC Channel