apiVersion: apps/v1
kind: Deployment # Create Dapr Deployment, will automatically have 2 pods (described below + daprd)
metadata:
  name: rw-server-openai
  labels: # Labels for the DEPLOYMENT, this way we can filter e.g. `kubectl delete -l key=value,key2=value2`
    app: d-rw-server-openai # deployment-roadwork-...
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p-rw-server-openai # Which pod will the deployment apply to?
  template:
    metadata:
      labels: # Labels for the POD
        app: p-rw-server-openai # pod-roadwork-...
      annotations:
        dapr.io/enabled: "true" # Do we inject a sidecar to this deployment?
        dapr.io/id: "id-rw-server-openai" # Unique ID or Name for Dapr App (so we can communicate with it)
        dapr.io/protocol: "grpc"
        dapr.io/port: "50050" # Port we are going to listen on (is app specific)
    spec:
      containers:
      - name: c-rw-server-openai # Name of our container, e.g. `kubectl logs -c c-rw-...`
        image: roadwork/rw-server-openai:latest
        imagePullPolicy: Never # in production PullIfNotPresent or Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: server-output
          mountPath: /mnt/output-server
      volumes:
      - name: server-output
        hostPath:
          path: /output # Local dir on PC
          type: DirectoryOrCreate # create empty dir if not exists